import { AdminGate } from "@/components/AdminGate";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BarChart3, Check, ClipboardList, FilePlus2, Loader2, Plus, Trash2, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type ExamForm = {
  title: string;
  subject: string;
  description: string;
  durationMinutes: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  status: "draft" | "published";
};
type QuestionForm = {
  prompt: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: string;
  position: string;
};
const blankExam: ExamForm = { title: "", subject: "", description: "", durationMinutes: "30", difficulty: "Intermediate", status: "draft" };
const blankQuestion: QuestionForm = { prompt: "", optionA: "", optionB: "", optionC: "", optionD: "", correctOption: "0", position: "1" };

function Metric({ icon: Icon, label, value, tone }: { icon: typeof BarChart3; label: string; value: number; tone: string }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></span><p className="font-display text-3xl font-semibold tracking-[-0.055em] text-slate-950 dark:text-white">{value}</p></div><p className="mt-4 text-sm font-semibold text-slate-600 dark:text-slate-300">{label}</p></div>;
}

function TextSelect({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="text-xs font-bold text-slate-500 dark:text-slate-400">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 outline-none focus:ring-2 focus:ring-emerald-500 dark:border-white/10 dark:bg-white/5 dark:text-white">{children}</select></label>;
}

export default function Admin() {
  const utils = trpc.useUtils();
  const { data: exams = [], isLoading: examsLoading } = trpc.admin.exams.useQuery();
  const { data: participation = [] } = trpc.admin.participation.useQuery();
  const [selectedExamId, setSelectedExamId] = useState<number | null>(null);
  const [editingExam, setEditingExam] = useState(false);
  const [editingQuestionId, setEditingQuestionId] = useState<number | null>(null);
  const { data: selected } = trpc.admin.examDetails.useQuery({ examId: selectedExamId ?? 0 }, { enabled: selectedExamId !== null });
  const [examForm, setExamForm] = useState<ExamForm>(blankExam);
  const [questionForm, setQuestionForm] = useState<QuestionForm>(blankQuestion);
  const refresh = async () => Promise.all([utils.admin.exams.invalidate(), utils.admin.participation.invalidate(), utils.admin.examDetails.invalidate()]);

  useEffect(() => {
    if (selected && editingExam) setExamForm({ title: selected.exam.title, subject: selected.exam.subject, description: selected.exam.description, durationMinutes: String(selected.exam.durationMinutes), difficulty: selected.exam.difficulty, status: selected.exam.status });
  }, [selected, editingExam]);
  useEffect(() => {
    if (selected && !editingQuestionId) setQuestionForm(current => ({ ...current, position: String(selected.questions.length + 1) }));
  }, [selected, editingQuestionId]);

  const createExam = trpc.admin.createExam.useMutation({ onSuccess: async id => { toast.success("Assessment created"); setSelectedExamId(id ?? null); setEditingExam(true); await refresh(); }, onError: error => toast.error(error.message) });
  const updateExam = trpc.admin.updateExam.useMutation({ onSuccess: async () => { toast.success("Assessment updated"); await refresh(); }, onError: error => toast.error(error.message) });
  const removeExam = trpc.admin.deleteExam.useMutation({ onSuccess: async () => { toast.success("Assessment removed"); setSelectedExamId(null); setEditingExam(false); setExamForm(blankExam); await refresh(); }, onError: error => toast.error(error.message) });
  const createQuestion = trpc.admin.createQuestion.useMutation({ onSuccess: async () => { toast.success("Question added"); setQuestionForm(blankQuestion); await refresh(); }, onError: error => toast.error(error.message) });
  const updateQuestion = trpc.admin.updateQuestion.useMutation({ onSuccess: async () => { toast.success("Question updated"); setQuestionForm(blankQuestion); setEditingQuestionId(null); await refresh(); }, onError: error => toast.error(error.message) });
  const removeQuestion = trpc.admin.deleteQuestion.useMutation({ onSuccess: async () => { toast.success("Question removed"); await refresh(); }, onError: error => toast.error(error.message) });
  const published = useMemo(() => exams.filter(exam => exam.status === "published").length, [exams]);
  const submitted = useMemo(() => participation.filter(row => row.status === "submitted").length, [participation]);

  const newAssessment = () => { setSelectedExamId(null); setEditingExam(false); setEditingQuestionId(null); setExamForm(blankExam); setQuestionForm(blankQuestion); };
  const selectAssessment = (examId: number) => { setSelectedExamId(examId); setEditingExam(true); setEditingQuestionId(null); setQuestionForm(blankQuestion); };
  const submitExam = (event: FormEvent) => {
    event.preventDefault();
    const values = { ...examForm, durationMinutes: Number(examForm.durationMinutes) };
    if (editingExam && selectedExamId) updateExam.mutate({ examId: selectedExamId, values }); else createExam.mutate(values);
  };
  const submitQuestion = (event: FormEvent) => {
    event.preventDefault();
    if (!selectedExamId) return toast.error("Select an assessment first");
    const values = { ...questionForm, correctOption: Number(questionForm.correctOption), position: Number(questionForm.position) };
    if (editingQuestionId) updateQuestion.mutate({ questionId: editingQuestionId, values }); else createQuestion.mutate({ ...values, examId: selectedExamId });
  };
  const editQuestion = (question: NonNullable<typeof selected>["questions"][number]) => { setEditingQuestionId(question.id); setQuestionForm({ prompt: question.prompt, optionA: question.optionA, optionB: question.optionB, optionC: question.optionC, optionD: question.optionD, correctOption: String(question.correctOption), position: String(question.position) }); };

  return <AdminGate><DashboardLayout><div className="mx-auto max-w-7xl px-5 py-7 sm:px-9 sm:py-10">
    <div><p className="text-xs font-bold uppercase tracking-[0.15em] text-emerald-700 dark:text-emerald-400">Content control</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-0.055em] sm:text-4xl">A calm view of your assessment space.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-400">Create, edit, and publish assessments while retaining learner records with safe content controls.</p></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={FilePlus2} label="Total assessments" value={exams.length} tone="bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300" /><Metric icon={Check} label="Published now" value={published} tone="bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300" /><Metric icon={UsersRound} label="Submitted attempts" value={submitted} tone="bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300" /></section>
    <section id="assessments" className="mt-10 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
      <form onSubmit={submitExam} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 dark:border-white/10 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><Plus className="size-[18px]" /></span><div className="min-w-0 flex-1"><h3 className="font-display text-xl font-semibold tracking-[-0.035em]">{editingExam ? "Edit assessment" : "Create an assessment"}</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{editingExam ? "Update the selected assessment." : "Save as a draft or publish when ready."}</p></div>{editingExam ? <Button type="button" variant="ghost" size="sm" onClick={newAssessment} className="rounded-lg text-xs">New</Button> : null}</div><div className="mt-6 space-y-4"><Input required value={examForm.title} onChange={event => setExamForm({ ...examForm, title: event.target.value })} placeholder="Assessment title" className="h-11 bg-slate-50 dark:bg-white/5" /><div className="grid gap-4 sm:grid-cols-2"><Input required value={examForm.subject} onChange={event => setExamForm({ ...examForm, subject: event.target.value })} placeholder="Subject / category" className="h-11 bg-slate-50 dark:bg-white/5" /><Input required type="number" min="1" max="360" value={examForm.durationMinutes} onChange={event => setExamForm({ ...examForm, durationMinutes: event.target.value })} placeholder="Minutes" className="h-11 bg-slate-50 dark:bg-white/5" /></div><Textarea required value={examForm.description} onChange={event => setExamForm({ ...examForm, description: event.target.value })} placeholder="A concise description for students" className="min-h-24 bg-slate-50 dark:bg-white/5" /><div className="grid gap-4 sm:grid-cols-2"><TextSelect label="Difficulty" value={examForm.difficulty} onChange={value => setExamForm({ ...examForm, difficulty: value as ExamForm["difficulty"] })}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></TextSelect><TextSelect label="Visibility" value={examForm.status} onChange={value => setExamForm({ ...examForm, status: value as ExamForm["status"] })}><option value="draft">Draft</option><option value="published">Published</option></TextSelect></div></div><Button type="submit" disabled={createExam.isPending || updateExam.isPending} className="mt-6 w-full rounded-xl bg-slate-950 font-semibold text-white dark:bg-white dark:text-slate-950">{createExam.isPending || updateExam.isPending ? "Saving…" : editingExam ? "Save changes" : "Create assessment"}<FilePlus2 className="ml-1.5 size-4" /></Button></form>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 dark:border-white/10"><div><h3 className="font-display text-xl font-semibold tracking-[-0.035em]">Your assessments</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">Select one to edit or manage its question set.</p></div><Badge className="rounded-full bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300">{exams.length} total</Badge></div>{examsLoading ? <div className="grid h-60 place-items-center"><Loader2 className="size-6 animate-spin text-emerald-600" /></div> : exams.length ? <div>{exams.map(exam => <button key={exam.id} onClick={() => selectAssessment(exam.id)} className={`flex w-full items-center gap-4 border-b border-slate-100 px-5 py-4 text-left transition-colors last:border-0 dark:border-white/10 ${selectedExamId === exam.id ? "bg-emerald-50/70 dark:bg-emerald-400/[0.07]" : "hover:bg-slate-50 dark:hover:bg-white/[0.03]"}`}><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-bold text-slate-600 dark:bg-white/10 dark:text-slate-300">{exam.questionCount}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900 dark:text-white">{exam.title}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{exam.subject} · {exam.durationMinutes} minutes · {exam.attemptCount} attempts</p></div><Badge className={`rounded-full ${exam.status === "published" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300" : "bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300"}`}>{exam.status}</Badge></button>)}</div> : <div className="grid h-60 place-items-center px-6 text-center"><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Create an assessment to start building your catalogue.</p></div>}</div>
    </section>
    <section id="questions" className="mt-10 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 dark:border-white/10 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><ClipboardList className="size-[18px]" /></span><div className="min-w-0 flex-1"><h3 className="font-display text-xl font-semibold tracking-[-0.035em]">{editingQuestionId ? "Edit question" : "Question builder"}</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{selected ? `${editingQuestionId ? "Editing" : "Adding to"} ${selected.exam.title}` : "Select an assessment above first."}</p></div>{editingQuestionId ? <Button type="button" variant="ghost" size="sm" onClick={() => { setEditingQuestionId(null); setQuestionForm(blankQuestion); }} className="rounded-lg text-xs">Cancel</Button> : null}</div><form onSubmit={submitQuestion} className="mt-6 space-y-4"><Textarea required disabled={!selected} value={questionForm.prompt} onChange={event => setQuestionForm({ ...questionForm, prompt: event.target.value })} placeholder="Write the question prompt" className="min-h-24 bg-slate-50 dark:bg-white/5" /><div className="grid gap-3 sm:grid-cols-2">{(["optionA", "optionB", "optionC", "optionD"] as const).map((key, index) => <div key={key} className="relative"><span className="absolute left-3 top-1/2 grid size-5 -translate-y-1/2 place-items-center rounded-full bg-slate-200 text-[9px] font-bold text-slate-600 dark:bg-white/10 dark:text-slate-300">{String.fromCharCode(65 + index)}</span><Input required disabled={!selected} value={questionForm[key]} onChange={event => setQuestionForm({ ...questionForm, [key]: event.target.value })} className="h-11 bg-slate-50 pl-10 dark:bg-white/5" placeholder={`Option ${String.fromCharCode(65 + index)}`} /></div>)}</div><div className="grid gap-4 sm:grid-cols-2"><TextSelect label="Correct answer" value={questionForm.correctOption} onChange={value => setQuestionForm({ ...questionForm, correctOption: value })}><option value="0">Option A</option><option value="1">Option B</option><option value="2">Option C</option><option value="3">Option D</option></TextSelect><label className="text-xs font-bold text-slate-500 dark:text-slate-400">Question order<Input required disabled={!selected} type="number" min="1" value={questionForm.position} onChange={event => setQuestionForm({ ...questionForm, position: event.target.value })} className="mt-1.5 h-10 bg-slate-50 dark:bg-white/5" /></label></div><Button type="submit" disabled={!selected || createQuestion.isPending || updateQuestion.isPending} className="w-full rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950">{createQuestion.isPending || updateQuestion.isPending ? "Saving question…" : editingQuestionId ? "Save question" : "Add question"}<Plus className="ml-1.5 size-4" /></Button></form></div>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 dark:border-white/10"><div><h3 className="font-display text-xl font-semibold tracking-[-0.035em]">Current question set</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{selected?.questions.length ?? 0} questions in this assessment.</p></div>{selected ? <Button variant="outline" size="sm" onClick={() => updateExam.mutate({ examId: selected.exam.id, values: { status: selected.exam.status === "published" ? "draft" : "published" } })} className="rounded-lg text-xs">{selected.exam.status === "published" ? "Move to draft" : "Publish"}</Button> : null}</div>{selected?.questions.length ? <div>{selected.questions.map(question => <div key={question.id} className="flex items-start gap-3 border-b border-slate-100 px-5 py-4 last:border-0 dark:border-white/10"><button onClick={() => editQuestion(question)} className="grid size-7 shrink-0 place-items-center rounded-lg bg-emerald-50 text-xs font-bold text-emerald-700 transition-transform hover:scale-105 dark:bg-emerald-400/10 dark:text-emerald-300" title="Edit question">{question.position}</button><button onClick={() => editQuestion(question)} className="min-w-0 flex-1 text-left"><p className="line-clamp-2 text-sm font-semibold leading-5 text-slate-800 hover:text-emerald-700 dark:text-white dark:hover:text-emerald-300">{question.prompt}</p><p className="mt-1.5 text-xs text-emerald-700 dark:text-emerald-400">Correct: {String.fromCharCode(65 + question.correctOption)} · {[question.optionA, question.optionB, question.optionC, question.optionD][question.correctOption]}</p></button><Button variant="ghost" size="icon" onClick={() => { if (window.confirm("Remove this question? Historical answer records are protected.")) removeQuestion.mutate({ questionId: question.id }); }} className="size-8 shrink-0 rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-400/10"><Trash2 className="size-4" /></Button></div>)}</div> : <div className="grid h-64 place-items-center px-6 text-center"><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">{selected ? "Add the first question using the builder." : "Select an assessment to view and manage its questions."}</p></div>}{selected ? <div className="border-t border-slate-100 p-4 dark:border-white/10"><Button variant="ghost" onClick={() => { if (window.confirm("Remove this assessment? Assessment records are protected after student participation.")) removeExam.mutate({ examId: selected.exam.id }); }} className="w-full rounded-lg text-sm font-semibold text-rose-600 hover:bg-rose-50 hover:text-rose-700 dark:hover:bg-rose-400/10"><Trash2 className="mr-1.5 size-4" />Delete this assessment</Button></div> : null}</div>
    </section>
    <section id="participation" className="mt-10 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 dark:border-white/10"><div><h3 className="font-display text-xl font-semibold tracking-[-0.035em]">Participation</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">Recent learner assessment activity.</p></div><BarChart3 className="size-5 text-emerald-600" /></div>{participation.length ? <div className="overflow-x-auto"><div className="min-w-[660px]"><div className="grid grid-cols-[1.2fr_1.3fr_0.7fr_0.6fr_0.9fr] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[10px] font-bold uppercase tracking-[0.13em] text-slate-500 dark:border-white/10 dark:bg-white/[0.03]"><span>Student</span><span>Assessment</span><span>Status</span><span>Score</span><span>Started</span></div>{participation.map(row => <div key={row.id} className="grid grid-cols-[1.2fr_1.3fr_0.7fr_0.6fr_0.9fr] gap-4 border-b border-slate-100 px-5 py-4 text-sm last:border-0 dark:border-white/10"><span className="truncate font-semibold text-slate-900 dark:text-white">{row.studentName || "Learner"}</span><span className="truncate text-slate-600 dark:text-slate-300">{row.examTitle}</span><Badge className={`w-fit rounded-full ${row.status === "submitted" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300" : "bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300"}`}>{row.status === "submitted" ? "Completed" : "In progress"}</Badge><span className="font-bold text-slate-900 dark:text-white">{row.status === "submitted" ? `${row.percentage}%` : "—"}</span><span className="text-xs text-slate-500 dark:text-slate-400">{new Date(row.startedAt).toLocaleDateString()}</span></div>)}</div></div> : <div className="grid h-48 place-items-center px-6 text-center"><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Participation records will appear after students start assessments.</p></div>}</section>
  </div></DashboardLayout></AdminGate>;
}
