import { SiteHeader } from "@/components/SiteHeader";
import { StudentGate } from "@/components/StudentGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { remainingSeconds } from "@/lib/timer";
import { toast } from "sonner";
import { AlertCircle, ArrowLeft, ArrowRight, CheckCircle2, Clock3, Flag, Loader2, Send, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRoute, useLocation } from "wouter";

function formatTime(seconds: number) { const minutes = Math.floor(seconds / 60); return `${String(minutes).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function ExamRunner() {
  const [, params] = useRoute("/exams/:examId/attempt/:attemptId");
  const [, setLocation] = useLocation();
  const attemptId = Number(params?.attemptId);
  const { data: session, isLoading } = trpc.attempts.session.useQuery({ attemptId }, { enabled: Number.isFinite(attemptId) && attemptId > 0 });
  const [activeIndex, setActiveIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [now, setNow] = useState(Date.now());
  const [showWarning, setShowWarning] = useState(false);
  const submittedRef = useRef(false);
  const saveMutation = trpc.attempts.saveAnswer.useMutation({ onError: error => toast.error(`Answer could not be saved: ${error.message}`) });
  const submitMutation = trpc.attempts.submit.useMutation({ onSuccess: result => { submittedRef.current = true; setLocation(`/results/${result.attemptId}`); }, onError: error => toast.error(`Assessment could not be submitted: ${error.message}`) });

  useEffect(() => { if (session) setAnswers(Object.fromEntries(session.answers.map(answer => [answer.questionId, answer.selectedOption]))); }, [session]);
  useEffect(() => { if (!session) return; const interval = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(interval); }, [session]);
  const secondsLeft = useMemo(() => session ? remainingSeconds(session.attempt.startedAt, session.exam.durationMinutes, now) : 0, [session, now]);
  const unanswered = session ? session.questions.filter(question => answers[question.id] === undefined).length : 0;
  const submit = useCallback(() => { if (!session || submittedRef.current || submitMutation.isPending) return; submitMutation.mutate({ attemptId: session.attempt.id }); }, [session, submitMutation]);
  useEffect(() => { if (session && secondsLeft === 0 && !submittedRef.current) submit(); }, [secondsLeft, session, submit]);

  const chooseAnswer = (questionId: number, selectedOption: number) => {
    setAnswers(current => ({ ...current, [questionId]: selectedOption }));
    saveMutation.mutate({ attemptId, questionId, selectedOption });
  };
  const requestSubmit = () => unanswered ? setShowWarning(true) : submit();

  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><SiteHeader /><StudentGate>{isLoading ? <div className="grid min-h-[65vh] place-items-center"><Loader2 className="size-7 animate-spin text-emerald-600" /></div> : !session ? <div className="container py-20 text-center"><h1 className="font-display text-3xl font-semibold text-slate-950 dark:text-white">This assessment is no longer active.</h1><Button className="mt-5 rounded-xl" onClick={() => setLocation("/exams")}>Return to catalogue</Button></div> : <main className="container py-6 sm:py-10"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 border-b border-slate-200 pb-5 dark:border-white/10 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge className="rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300">{session.exam.subject}</Badge><span className="text-xs font-semibold text-slate-400">Question {activeIndex + 1} of {session.questions.length}</span></div><h1 className="mt-2 font-display text-2xl font-semibold tracking-[-0.045em] text-slate-950 sm:text-3xl dark:text-white">{session.exam.title}</h1></div><div className={`flex items-center gap-3 self-start rounded-xl border px-3.5 py-2.5 ${secondsLeft < 60 ? "border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-400/30 dark:bg-rose-400/10 dark:text-rose-300" : "border-slate-200 bg-white text-slate-800 dark:border-white/10 dark:bg-slate-900 dark:text-white"}`}><Clock3 className="size-[18px]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] opacity-60">Time remaining</p><p className="font-mono text-lg font-bold tracking-tight">{formatTime(secondsLeft)}</p></div></div></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_260px]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8 dark:border-white/10 dark:bg-slate-900"><Progress value={((activeIndex + 1) / session.questions.length) * 100} className="h-1.5 bg-slate-100 dark:bg-white/10" /><p className="mt-7 text-sm font-bold uppercase tracking-[0.13em] text-emerald-700 dark:text-emerald-400">Question {activeIndex + 1}</p><h2 className="mt-3 max-w-3xl font-display text-xl font-semibold leading-[1.25] tracking-[-0.035em] text-slate-950 sm:text-2xl dark:text-white">{session.questions[activeIndex]?.prompt}</h2><div className="mt-7 grid gap-3">{session.questions[activeIndex]?.options.map((option, index) => { const selected = answers[session.questions[activeIndex].id] === index; return <button key={option} onClick={() => chooseAnswer(session.questions[activeIndex].id, index)} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition-all duration-200 ${selected ? "border-emerald-500 bg-emerald-50/70 shadow-[0_8px_20px_-16px_rgba(16,185,129,0.7)] dark:border-emerald-400 dark:bg-emerald-400/10" : "border-slate-200 bg-white hover:border-emerald-200 hover:bg-emerald-50/40 dark:border-white/10 dark:bg-slate-900 dark:hover:border-emerald-400/30 dark:hover:bg-white/[0.03]"}`}><span className={`grid size-7 shrink-0 place-items-center rounded-full border text-xs font-bold ${selected ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300 text-slate-500 dark:border-slate-600 dark:text-slate-400"}`}>{String.fromCharCode(65 + index)}</span><span className="text-sm font-medium leading-6 text-slate-700 dark:text-slate-200">{option}</span>{selected ? <CheckCircle2 className="ml-auto size-5 text-emerald-600 dark:text-emerald-400" /> : null}</button>; })}</div><div className="mt-8 flex items-center justify-between gap-3 border-t border-slate-100 pt-5 dark:border-white/10"><Button variant="outline" onClick={() => setActiveIndex(index => Math.max(0, index - 1))} disabled={activeIndex === 0} className="rounded-xl border-slate-200 dark:border-white/15"><ArrowLeft className="mr-1.5 size-4" />Previous</Button>{activeIndex < session.questions.length - 1 ? <Button onClick={() => setActiveIndex(index => Math.min(session.questions.length - 1, index + 1))} className="rounded-xl bg-slate-950 text-white hover:bg-slate-800 dark:bg-white dark:text-slate-950">Next<ArrowRight className="ml-1.5 size-4" /></Button> : <Button onClick={requestSubmit} disabled={submitMutation.isPending} className="rounded-xl bg-emerald-600 text-white hover:bg-emerald-700">{submitMutation.isPending ? "Submitting…" : "Submit assessment"}<Send className="ml-1.5 size-4" /></Button>}</div></section>
    <aside className="order-first rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:order-last dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between"><p className="text-sm font-bold text-slate-900 dark:text-white">Your progress</p><span className="text-xs font-semibold text-slate-500 dark:text-slate-400">{session.questions.length - unanswered}/{session.questions.length} answered</span></div><div className="mt-4 grid grid-cols-6 gap-2 lg:grid-cols-5">{session.questions.map((question, index) => <button key={question.id} onClick={() => setActiveIndex(index)} aria-label={`Go to question ${index + 1}`} className={`grid aspect-square place-items-center rounded-lg text-xs font-bold transition-all ${activeIndex === index ? "bg-slate-950 text-white dark:bg-emerald-400 dark:text-slate-950" : answers[question.id] !== undefined ? "bg-emerald-100 text-emerald-800 hover:bg-emerald-200 dark:bg-emerald-400/15 dark:text-emerald-300" : "bg-slate-100 text-slate-500 hover:bg-slate-200 dark:bg-white/10 dark:text-slate-300"}`}>{index + 1}</button>)}</div><div className="mt-5 space-y-2 border-t border-slate-100 pt-4 text-xs text-slate-500 dark:border-white/10 dark:text-slate-400"><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-500" />Answered</p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-slate-300 dark:bg-slate-600" />Not answered</p></div><Button onClick={requestSubmit} disabled={submitMutation.isPending} variant="outline" className="mt-6 w-full rounded-xl border-emerald-200 text-emerald-700 hover:bg-emerald-50 dark:border-emerald-400/30 dark:text-emerald-300 dark:hover:bg-emerald-400/10"><Flag className="mr-1.5 size-4" />Finish & submit</Button><p className="mt-4 flex gap-2 text-[11px] leading-5 text-slate-400"><ShieldCheck className="mt-0.5 size-3.5 shrink-0" />Answers are saved as you move through the assessment.</p></aside></div>
    {showWarning ? <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><span className="grid size-10 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300"><AlertCircle className="size-5" /></span><h3 className="mt-4 font-display text-xl font-semibold tracking-[-0.035em] text-slate-950 dark:text-white">{unanswered} question{unanswered === 1 ? "" : "s"} still unanswered</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">You can return to those questions now, or submit the assessment with the answers you have selected.</p><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={() => setShowWarning(false)} className="rounded-xl">Review answers</Button><Button onClick={submit} className="rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950">Submit anyway</Button></div></div></div> : null}
  </div></main>}</StudentGate></div>;
}
