import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { motion } from "framer-motion";
import { ArrowRight, BookOpenCheck, Brain, BriefcaseBusiness, CheckCircle2, ChevronRight, Clock3, Code2, Compass, FlaskConical, Globe2, History, Landmark, Play, ShieldCheck, Sparkles, Trophy, UsersRound } from "lucide-react";
import { Link, useLocation } from "wouter";

const fadeUp = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };
const subjects = [
  { name: "Mathematics", icon: Brain }, { name: "Science", icon: FlaskConical }, { name: "English", icon: BookOpenCheck },
  { name: "History", icon: Landmark }, { name: "Programming", icon: Code2 }, { name: "Business", icon: BriefcaseBusiness },
];

function EmptyExamCard() { return <div className="min-h-20 rounded-xl border border-slate-200 border-l-4 border-l-emerald-500 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="h-3 w-32 rounded bg-slate-200 dark:bg-white/10" /><div className="mt-2 h-2.5 w-20 rounded bg-slate-100 dark:bg-white/[0.06]" /></div><Badge className="rounded-full bg-slate-100 text-[10px] text-slate-600 dark:bg-white/10 dark:text-slate-300">Coming soon</Badge></div></div>; }

export default function Home() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const { data: exams = [] } = trpc.exams.list.useQuery();
  const { data: leaderboard = [] } = trpc.attempts.leaderboard.useQuery({ subject: "", period: "all" });
  const startMutation = trpc.attempts.start.useMutation({ onSuccess: result => setLocation(`/exams/${featured[0]?.id ?? "active"}/attempt/${result.attemptId}`) });
  const featured = exams.slice(0, 3);
  const startFirst = () => { if (!user) return startLogin(); if (featured[0]) startMutation.mutate({ examId: featured[0].id }); else setLocation("/exams"); };

  return <div className="min-h-screen overflow-x-hidden bg-[hsl(var(--page))] text-slate-950 dark:text-slate-50"><SiteHeader /><main>
    <section className="relative overflow-hidden"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="container relative grid min-h-[560px] items-center gap-12 py-16 sm:py-20 lg:grid-cols-[0.92fr_1.08fr]">
      <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.08 } } }} className="relative z-10 max-w-xl"><motion.div variants={fadeUp}><Badge className="rounded-full border-0 bg-emerald-100 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-800 shadow-none dark:bg-emerald-400/15 dark:text-emerald-300"><Sparkles className="mr-1.5 size-3" />Assessment, considered</Badge></motion.div><motion.h1 variants={fadeUp} className="mt-6 font-display text-[clamp(3.2rem,5.1vw,4.6rem)] font-semibold leading-[0.96] tracking-[-0.06em] text-slate-950 dark:text-white">Assess with <span className="text-emerald-600 dark:text-emerald-400">clarity.</span><br />Grow with intent.</motion.h1><motion.p variants={fadeUp} className="mt-6 max-w-[520px] text-base leading-7 text-slate-600 sm:text-lg dark:text-slate-300">Discover well-structured assessments, stay focused in a calm exam room, and turn every result into your next best step.</motion.p><motion.div variants={fadeUp} className="mt-8 flex flex-col gap-4 sm:flex-row"><Button onClick={startFirst} disabled={startMutation.isPending} size="lg" className="rounded-xl bg-slate-950 px-6 font-semibold text-white shadow-[0_12px_24px_-12px_rgba(15,23,42,0.7)] hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-100">{startMutation.isPending ? "Preparing assessment…" : user ? "Start an assessment" : "Begin your journey"}<ArrowRight className="ml-1.5 size-4" /></Button><Button asChild variant="outline" size="lg" className="rounded-xl border-slate-200 bg-white/50 px-6 font-semibold text-slate-800 hover:bg-white dark:border-white/15 dark:bg-white/5 dark:text-white dark:hover:bg-white/10"><Link href="/exams"><Compass className="mr-1.5 size-4" />Explore catalogue</Link></Button></motion.div><motion.div variants={fadeUp} className="mt-12 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-slate-600 dark:text-slate-300"><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Timed assessment flow</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Personal result history</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="size-4 text-emerald-600" />Role-secured platform</span></motion.div></motion.div>
      <motion.div initial={{ opacity: 0, scale: 0.96, x: 16 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.15, ease: [0.23, 1, 0.32, 1] }} className="relative mx-auto w-full max-w-2xl lg:translate-x-8"><div className="absolute -inset-8 rounded-[3rem] bg-emerald-400/15 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/70 bg-slate-900 shadow-[0_30px_100px_-25px_rgba(15,23,42,0.45)] dark:border-white/10"><img src="/manus-storage/examora-hero-illustration_a0ceefab.png" alt="Students completing a digital assessment" className="aspect-[16/10] w-full object-cover" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-slate-950/75 via-slate-950/15 to-transparent px-5 pb-5 pt-16 text-white sm:px-7 sm:pb-7"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-emerald-300">Examora space</p><p className="mt-1 font-display text-xl font-semibold tracking-[-0.04em]">A quiet place to show what you know.</p></div><span className="hidden size-11 place-items-center rounded-full border border-white/20 bg-white/10 backdrop-blur sm:grid"><Play className="ml-0.5 size-4 fill-current" /></span></div></div><div className="absolute -bottom-5 -left-4 hidden rounded-2xl border border-white/80 bg-white/95 p-3.5 shadow-xl backdrop-blur md:block dark:border-white/10 dark:bg-slate-900/95"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300"><Clock3 className="size-4" /></span><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Focus mode</p><p className="text-[15px] font-bold text-slate-800 dark:text-white">Every minute matters</p></div></div></div></motion.div>
    </div></section>
    <section className="border-y border-slate-200 bg-white py-6 dark:border-white/10 dark:bg-slate-900/50"><div className="container grid gap-4 text-center sm:grid-cols-3 sm:text-left">{[[BookOpenCheck,"Purposeful practice","Curated, structured assessments","emerald"],[Trophy,"Meaningful feedback","Clear outcome summaries","violet"],[ShieldCheck,"Secure by role","Student and admin access controls","sky"]].map(([Icon,title,copy,tone]) => <div key={String(title)} className="flex items-center justify-center gap-3 sm:justify-start"><span className={`grid size-8 place-items-center rounded-xl bg-${tone}-50 text-${tone}-700 dark:bg-${tone}-400/10 dark:text-${tone}-300`}><Icon className="size-5" /></span><div><p className="text-[15px] font-bold">{String(title)}</p><p className="text-[13px] text-slate-500 dark:text-slate-400">{String(copy)}</p></div></div>)}</div></section>
    <section className="container py-18 sm:py-20"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">Your path</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-4xl dark:text-white">Three steps to a clearer result.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{[["01","Browse the catalogue","Filter by subject, difficulty, or time available and find the assessment that fits your goal."],["02","Enter the exam room","A distraction-free, timed environment built to help you focus and perform at your best."],["03","Review your results","Get an instant outcome summary with your score and areas to revisit."]].map(([number,title,copy]) => <article key={number} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><span className="grid size-10 place-items-center rounded-full bg-slate-950 text-xs font-bold text-white dark:bg-emerald-400 dark:text-slate-950">{number}</span><h3 className="mt-6 font-display text-xl font-semibold text-slate-950 dark:text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{copy}</p></article>)}</div></section>
    <section className="container py-18 sm:py-20"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">The catalogue</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-4xl dark:text-white">What will you be assessed on?</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{subjects.map(({ name, icon: Icon }) => <Link key={name} href="/exams" className="group flex h-[200px] flex-col rounded-xl border border-slate-200 bg-white p-5 transition-all hover:-translate-y-1 hover:border-emerald-300 hover:shadow-lg dark:border-white/10 dark:bg-slate-900 dark:hover:border-emerald-400/35"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-xl font-semibold text-slate-950 dark:text-white">{name}</h3><span className="mt-auto inline-flex items-center text-sm font-bold text-emerald-700 group-hover:text-emerald-600 dark:text-emerald-300">Explore <ChevronRight className="ml-1 size-4" /></span></Link>)}</div></section>
    <section className="container py-18 sm:py-20"><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900 lg:grid lg:grid-cols-2"><div className="p-6 sm:p-9"><div className="flex flex-wrap gap-2"><Badge className="rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300">Critical thinking</Badge><Badge variant="outline" className="rounded-full">Intermediate</Badge></div><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">Critical Thinking: Foundations</h2><p className="mt-4 max-w-md text-sm leading-6 text-slate-600 dark:text-slate-400">See the calm, clear MCQ format learners encounter before they begin a timed assessment.</p><div className="mt-6 flex gap-5 text-sm font-semibold text-slate-600 dark:text-slate-300"><span className="inline-flex items-center gap-1.5"><Clock3 className="size-4 text-emerald-600" />25 min</span><span className="inline-flex items-center gap-1.5"><BookOpenCheck className="size-4 text-emerald-600" />20 questions</span></div><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="outline" className="rounded-xl"><Link href="/exams">Preview exam <ArrowRight className="ml-1.5 size-4" /></Link></Button><Button onClick={startFirst} className="rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950">Start now <ArrowRight className="ml-1.5 size-4" /></Button></div></div><div className="bg-slate-50 p-6 dark:bg-slate-950/40 sm:p-9"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">Question preview</p><p className="mt-4 font-display text-xl font-semibold text-slate-950 dark:text-white">Which response best evaluates an argument?</p><div className="mt-6 space-y-2">{["Accept its conclusion without evidence", "Consider evidence, assumptions, and alternatives", "Choose the longest answer", "Focus only on the speaker"].map((answer,index) => <div key={answer} className={`flex items-center gap-3 rounded-xl border p-3 text-sm ${index === 1 ? "border-emerald-300 bg-emerald-50 text-emerald-900 dark:border-emerald-400/35 dark:bg-emerald-400/10 dark:text-emerald-100" : "border-slate-200 bg-white text-slate-600 dark:border-white/10 dark:bg-slate-900 dark:text-slate-300"}`}><span className="grid size-6 place-items-center rounded-full border text-xs font-bold">{String.fromCharCode(65 + index)}</span>{answer}</div>)}</div></div></div></section>
    <section className="container py-18 sm:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">Leaderboard</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-4xl dark:text-white">See where you rank.</h2></div><Button asChild variant="outline" className="w-fit rounded-xl"><Link href="/leaderboard">View full leaderboard <ArrowRight className="ml-1.5 size-4" /></Link></Button></div><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-white/10 dark:bg-slate-900">{leaderboard.length ? leaderboard.slice(0,5).map(entry => <div key={`${entry.rank}-${entry.name}`} className={`grid grid-cols-[42px_1fr_auto] items-center gap-3 px-5 py-4 text-sm ${entry.rank === 1 ? "bg-emerald-50/80 dark:bg-emerald-400/[0.08]" : "odd:bg-slate-50/70 dark:odd:bg-white/[0.02]"}`}><span className={`grid size-8 place-items-center rounded-full font-bold ${entry.rank === 1 ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300"}`}>{entry.rank}</span><span><b className="text-slate-900 dark:text-white">{entry.name}</b><small className="ml-2 text-slate-500">{entry.subject}</small></span><span className="font-bold text-emerald-700 dark:text-emerald-300">{entry.percentage}%</span></div>) : <div className="grid min-h-28 place-items-center p-6 text-center"><div><UsersRound className="mx-auto size-5 text-emerald-600" /><p className="mt-3 font-semibold text-slate-800 dark:text-white">Live rankings will appear here.</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Complete an assessment to contribute to the leaderboard.</p></div></div>}</div></section>
    <section className="container py-18 sm:py-20"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">Learning experience</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-4xl dark:text-white">Designed for focused progress.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{[[Clock3,"Calm exam room","A clear, timed interface keeps attention on the work in front of you."],[History,"Progress retained","Results, reviews, and eligible documents remain available in your history."],[Globe2,"Accessible anywhere","Responsive layouts make assessment review practical across desktop, tablet, and mobile."]].map(([Icon,title,copy]) => <article key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><Icon className="size-5 text-emerald-600 dark:text-emerald-300" /><h3 className="mt-5 font-display text-xl font-semibold text-slate-950 dark:text-white">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{String(copy)}</p></article>)}</div></section>
    <section className="bg-[#0D1117] py-10 text-white"><div className="container grid gap-6 text-center sm:grid-cols-3 sm:divide-x sm:divide-white/15">{[["Timed","assessment flow"],["Instant","outcome review"],["Private","learning history"]].map(([value,label]) => <div key={value} className="px-6"><p className="font-display text-4xl font-semibold text-emerald-400">{value}</p><p className="mt-2 text-sm text-slate-300">{label}</p></div>)}</div></section>
    <section className="container py-18 sm:py-20"><div className="overflow-hidden rounded-[2rem] bg-slate-950 px-7 py-10 text-white shadow-[0_30px_80px_-38px_rgba(15,23,42,0.8)] sm:px-12 sm:py-14 lg:grid lg:grid-cols-[1fr_auto] lg:items-center lg:gap-12"><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-300">A better assessment rhythm</p><h2 className="mt-3 max-w-xl font-display text-3xl font-semibold tracking-[-0.055em] sm:text-4xl">Know exactly where you stand—and where you can go next.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300">Answer with focus, receive an immediate result, and retain a private history of the work you have completed.</p></div><Button asChild className="mt-7 h-11 rounded-xl bg-emerald-400 px-5 font-bold text-slate-950 hover:bg-emerald-300 lg:mt-0"><Link href="/exams">Find an assessment <ArrowRight className="ml-1.5 size-4" /></Link></Button></div></section>
    <section className="container py-18 sm:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-400">Find your focus</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-4xl dark:text-white">Explore live assessments.</h2></div><Button asChild variant="ghost" className="w-fit rounded-full text-sm font-bold text-slate-700 hover:bg-slate-100 hover:text-emerald-700 dark:text-slate-200 dark:hover:bg-white/10 dark:hover:text-emerald-300"><Link href="/exams">View the catalogue <ArrowRight className="ml-1.5 size-4" /></Link></Button></div><div className="mt-8 grid gap-4 md:grid-cols-3">{featured.length ? featured.map(exam => <Link key={exam.id} href="/exams" className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-all hover:-translate-y-1 hover:border-emerald-200 dark:border-white/10 dark:bg-slate-900 dark:hover:border-emerald-400/30"><div className="flex items-center justify-between gap-3"><Badge className="rounded-full bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300">{exam.subject}</Badge><ArrowRight className="size-4 text-slate-400 group-hover:text-emerald-600" /></div><h3 className="mt-4 font-display text-lg font-semibold text-slate-950 dark:text-white">{exam.title}</h3><p className="mt-3 text-xs font-medium text-slate-500 dark:text-slate-400">{exam.questionCount} questions · {exam.durationMinutes} min · {exam.difficulty}</p></Link>) : <><EmptyExamCard /><EmptyExamCard /><EmptyExamCard /></>}</div></section>
  </main><SiteFooter /></div>;
}
