import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { Button } from "@/components/ui/button";
import { ArrowRight, BookOpenCheck, Mail, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";

export function About() { return <div className="min-h-screen bg-[hsl(var(--page))]"><SiteHeader /><main className="container py-10 sm:py-12"><div className="mx-auto max-w-none"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700 dark:text-emerald-400">About Examora</p><h1 className="mt-3 font-display text-5xl font-semibold leading-[0.98] tracking-[-0.065em] text-slate-950 sm:text-5xl xl:whitespace-nowrap dark:text-white">Assessment should leave learners <span className="text-emerald-600 dark:text-emerald-400">clearer.</span></h1><p className="mt-5 max-w-none text-sm leading-6 text-slate-600 xl:whitespace-nowrap dark:text-slate-300">Examora is designed around a simple idea: when an assessment is calm, structured, and fair, learners can focus on demonstrating knowledge rather than navigating friction.</p><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[BookOpenCheck,"Structured","Discover purposeful assessments."],[ShieldCheck,"Secure","Role-aware access protects content."],[Sparkles,"Reflective","Turn a result into your next step."]].map(([Icon,label,copy]) => { const ItemIcon = Icon as typeof BookOpenCheck; return <div key={label as string} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900"><ItemIcon className="size-5 text-emerald-600" /><p className="mt-4 font-display text-lg font-semibold tracking-[-0.035em] dark:text-white">{label as string}</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{copy as string}</p></div>; })}</div><Button asChild className="mt-8 rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950"><Link href="/exams">Explore assessments <ArrowRight className="ml-1.5 size-4" /></Link></Button></div></main><SiteFooter /></div>; }

export function Contact() { return <div className="min-h-screen bg-[hsl(var(--page))]"><SiteHeader /><main className="container grid min-h-[68vh] place-items-center py-16 sm:py-24"><div className="w-full max-w-2xl rounded-[2rem] border border-slate-200 bg-white p-8 text-center shadow-[0_24px_60px_-38px_rgba(15,23,42,0.4)] sm:p-12 dark:border-white/10 dark:bg-slate-900"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><Mail className="size-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-emerald-700 dark:text-emerald-400">Contact</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-0.06em] text-slate-950 sm:text-5xl dark:text-white">Let’s make assessment easier.</h1><p className="mx-auto mt-5 max-w-lg text-base leading-7 text-slate-600 dark:text-slate-300">For platform questions, assessment support, or administration enquiries, please contact your programme coordinator or platform administrator.</p><Button asChild variant="outline" className="mt-8 rounded-xl border-slate-200 bg-white font-semibold dark:border-white/15 dark:bg-white/5"><a href="mailto:hello@examora.example">hello@examora.example <ArrowRight className="ml-1.5 size-4" /></a></Button></div></main><SiteFooter /></div>; }
