import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { StudentDocumentActions } from "@/components/StudentDocumentActions";
import { StudentGate } from "@/components/StudentGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ChartContainer } from "@/components/ui/chart";
import { trpc } from "@/lib/trpc";
import { hasPassedAssessment } from "@shared/assessmentEligibility";
import { buildPerformanceTrend } from "@shared/examEnhancements";
import { useAuth } from "@/_core/hooks/useAuth";
import { Award, BarChart3, CalendarDays, ChevronRight, FileText, Loader2, Sparkles, Trophy } from "lucide-react";
import { useMemo } from "react";
import { CartesianGrid, Line, LineChart, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";

const chartConfig = { percentage: { label: "Achievement", color: "#10b981" } };

export default function Profile() {
  const { user } = useAuth();
  const { data: history = [], isLoading: historyLoading } = trpc.attempts.history.useQuery();
  const { data: documents = [], isLoading: documentsLoading } = trpc.attempts.documents.useQuery();
  const trend = useMemo(() => buildPerformanceTrend(history), [history]);
  const completed = history.filter(item => item.status === "submitted");
  const certificates = documents.filter(item => hasPassedAssessment(item.percentage));
  const average = completed.length ? Math.round(completed.reduce((total, item) => total + item.percentage, 0) / completed.length) : 0;
  const best = completed.length ? Math.max(...completed.map(item => item.percentage)) : 0;
  const loading = historyLoading || documentsLoading;

  return <div className="min-h-screen bg-[hsl(var(--page))]"><SiteHeader /><StudentGate><main className="container py-10 sm:py-16">{loading ? <div className="grid min-h-[60vh] place-items-center"><Loader2 className="size-7 animate-spin text-emerald-600" /></div> : <div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-9 text-white sm:px-10 sm:py-12"><div className="absolute -right-16 -top-20 size-72 rounded-full bg-emerald-400/15 blur-3xl" /><div className="relative"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Student profile</p><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="font-display text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">{user?.name || "Your"} learning story.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300">Track completed assessments, download achievement documents, and see the momentum behind your results.</p></div><Button asChild variant="outline" className="w-fit rounded-xl border-white/20 bg-white/10 text-white hover:bg-white/15 hover:text-white"><Link href="/exams"><Sparkles className="mr-1.5 size-4" />Explore assessments</Link></Button></div></div></section><section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={BarChart3} value={`${average}%`} label="Average achievement" tone="emerald" /><Metric icon={Trophy} value={`${best}%`} label="Best recorded result" tone="amber" /><Metric icon={Award} value={String(certificates.length)} label="Eligible certificates" tone="emerald" /></section><section className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><TrendPanel trend={trend} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 dark:border-white/10 dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700 dark:text-emerald-400">Certificate library</p><h2 className="mt-1 font-display text-2xl font-semibold tracking-[-0.04em] text-slate-950 dark:text-white">Your achievements.</h2>{certificates.length ? <div className="mt-5 space-y-3">{certificates.slice(0, 4).map(item => <div key={item.attemptId} className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-4 dark:border-emerald-400/20 dark:bg-emerald-400/[0.06]"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-emerald-600 text-white"><Award className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900 dark:text-white">{item.examTitle}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{item.subject} · {item.percentage}%</p></div></div><StudentDocumentActions result={item} studentName={user?.name || "Examora Learner"} /></div>)}</div> : <EmptyCertificates />}</section></section><HistoryPanel completed={completed} /></div>}</main></StudentGate><SiteFooter /></div>;
}

function Metric({ icon: Icon, value, label, tone }: { icon: typeof BarChart3; value: string; label: string; tone: "emerald" | "amber" }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900"><Icon className={`size-5 ${tone === "amber" ? "text-amber-500" : "text-emerald-600"}`} /><p className="mt-4 font-display text-3xl font-semibold tracking-[-0.055em] text-slate-950 dark:text-white">{value}</p><p className="mt-1 text-sm font-semibold text-slate-600 dark:text-slate-300">{label}</p></div>; }
function TrendPanel({ trend }: { trend: ReturnType<typeof buildPerformanceTrend> }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 dark:border-white/10 dark:bg-slate-900"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700 dark:text-emerald-400">Performance trends</p><h2 className="mt-1 font-display text-2xl font-semibold tracking-[-0.04em] text-slate-950 dark:text-white">Your results over time.</h2></div><Badge className="rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300">{trend.length} completed</Badge></div>{trend.length ? <ChartContainer config={chartConfig} className="mt-6 h-[280px] w-full"><LineChart data={trend} margin={{ left: -15, right: 10, top: 8, bottom: 0 }}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tickMargin={9} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tickMargin={8} width={30} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid rgba(148,163,184,.25)", boxShadow: "0 16px 35px -18px rgba(15,23,42,.35)" }} formatter={(value: number) => [`${value}%`, "Achievement"]} labelFormatter={(_, payload) => payload?.[0]?.payload?.assessment || "Assessment"} /><Line type="monotone" dataKey="percentage" stroke="var(--color-percentage)" strokeWidth={3} dot={{ r: 4, fill: "var(--color-percentage)" }} activeDot={{ r: 6 }} /></LineChart></ChartContainer> : <div className="mt-6 grid min-h-64 place-items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center dark:border-white/15 dark:bg-white/[0.03]"><div><BarChart3 className="mx-auto size-6 text-slate-400" /><p className="mt-3 font-display text-lg font-semibold text-slate-900 dark:text-white">Your trend will appear here.</p><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">Complete assessments to build a visual record of your performance.</p></div></div>}</section>; }
function EmptyCertificates() { return <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center dark:border-white/15 dark:bg-white/[0.03]"><Award className="mx-auto size-5 text-slate-400" /><p className="mt-3 text-sm font-semibold text-slate-900 dark:text-white">No certificates yet</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Pass an assessment with 65% or higher to unlock your first certificate and report.</p></div>; }
function HistoryPanel({ completed }: { completed: { id: number; examTitle: string; subject: string; score: number; totalQuestions: number; percentage: number; submittedAt: Date | string | null }[] }) { return <section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 dark:border-white/10"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700 dark:text-emerald-400">Assessment history</p><h2 className="mt-1 font-display text-2xl font-semibold tracking-[-0.04em] text-slate-950 dark:text-white">Your completed record.</h2></div><FileText className="size-5 text-emerald-600" /></div>{completed.length ? <div>{completed.map(item => <Link key={item.id} href={`/results/${item.id}`} className="flex items-center gap-4 border-b border-slate-100 px-5 py-4 transition-colors last:border-0 hover:bg-slate-50 dark:border-white/10 dark:hover:bg-white/[0.03]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300"><CalendarDays className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900 dark:text-white">{item.examTitle}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{item.subject} · {item.submittedAt ? new Date(item.submittedAt).toLocaleDateString() : "Completed"}</p></div><div className="text-right"><p className="font-display text-xl font-semibold tracking-[-0.04em] text-slate-950 dark:text-white">{item.percentage}%</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{item.score}/{item.totalQuestions} correct</p></div><ChevronRight className="size-4 text-slate-400" /></Link>)}</div> : <div className="grid min-h-52 place-items-center p-6 text-center"><div><p className="font-display text-lg font-semibold text-slate-900 dark:text-white">Your completed assessments will be shown here.</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Start an assessment to build your learning record.</p></div></div>}</section>; }
